OUTPUT_FILE="Q3/commits.txt"
echo "$COMMIT_MSG" >> "$OUTPUT_FILE"
echo "Commit saved to $OUTPUT_FILE"

echo "$COMMIT_MSG"

CURR_DATE=$(date +"%Y-%m-%d %H:%M:%S")


ADDITIONAL_DESCRIPTION="$1"
CSV_FILE="Q3/bugs.csv"


COMMIT_MSG="BugID:$BUGID|$CURR_DATE|$BRANCH|$DEV_NAME|$PRIORITY|$DESCRIPTION|$ADDITIONAL_DESCRIPTION"
